---
version: "3.8"
services:
  grpc-server:
    image: dhavalsalwala/forecasting-grpc-server:latest
    hostname: grpc-server
    container_name: grpc
    network_mode: host
    build:
      context: "."
    shm_size: "10.24gb"
    tty:
      true
    ports:
      - 50051:50051
    environment:
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_GRPC_CONSUMER_QUEUE: ${RABBITMQ_GRPC_CONSUMER_QUEUE}
      RABBITMQ_GRPC_PRODUCER_QUEUE: ${RABBITMQ_GRPC_PRODUCER_QUEUE}
      GRPC_HOST: ${GRPC_HOST}
      GRPC_PORT: ${GRPC_PORT}
    entrypoint: ["python", "serving/grpc_server.py", "--data_dir", "/data", "--config_dir", "/config"]
    volumes:
      - /home/dhaval/dev/forecasting-service/data:/data
      - /home/dhaval/dev/forecasting-service/examples:/config

# networks:
#   default:
#     name: more-network
#     external: true
